### PR TITLE
Substreams GUI

### PR DESCRIPTION
**Pull request by abourget**
First draft of https://github.com/streamingfast/planning/issues/152

Missing:
* proper display of errors from module's execution 
* Initial snapshot display

Then next steps:
* Searching in payloads
* Display of request info tab

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Perhaps installation issue, but whenever launch the GUI option and press `Tab`, it crashes 🤷‍♂️ 

- Installed instructions via: `go install -v ./cmd/substreams `
- OS: macOS Ventura

image

## ❌ Pressing `Tab` error logs

```
Launching Substreams GUI...
Caught panic:

runtime error: index out of range [118] with length 118

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/Users/denis/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.1/tea.go:383 +0x8c
panic({0x105956dc0, 0x140025c4a08})
	/opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/panic.go:890 +0x258
github.com/streamingfast/substreams/tui2/components/blockselect.(*BlockSelect).View(0x14000c90a50)
	/Users/denis/Github/substreams-cli/tui2/components/blockselect/blockselect.go:104 +0x5f4
github.com/streamingfast/substreams/tui2/pages/output.(*Output).View(0x14000782780)
	/Users/denis/Github/substreams-cli/tui2/pages/output/output.go:158 +0x48
github.com/streamingfast/substreams/tui2.(*UI).View(0x14000d40f80)
	/Users/denis/Github/substreams-cli/tui2/ui.go:167 +0x38c
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x14000cce630, {0x105aa6de8?, 0x14000d40f80?}, 0x7?)
	/Users/denis/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.1/tea.go:326 +0x5c8
github.com/charmbracelet/bubbletea.(*Program).Run(0x14000cce630)
	/Users/denis/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.23.1/tea.go:446 +0x6b0
main.runGui(0x106b0e740?, {0x140009bda90?, 0x1?, 0x5?})
	/Users/denis/Github/substreams-cli/cmd/substreams/gui.go:158 +0xa44
github.com/spf13/cobra.(*Command).execute(0x106b0e740, {0x140009bda40, 0x5, 0x5})
	/Users/denis/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x106b0dbc0)
	/Users/denis/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/denis/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/Users/denis/Github/substreams-cli/cmd/substreams/main.go:21 +0x90
```

**Comment by abourget** [comment]
Ok just fixed your issue with 58f91cf

**Comment by DenisCarriere** [comment]
New fixes work 👍  can `Tab` in-between windows now

No errors founds exiting the CLI

image

image

image

**Comment by YaroShkvorets** [comment]
Output progress bar goes crazy sometimes, I think.
This is after it finished streaming.

image

**Comment by DenisCarriere** [comment]
@YaroShkvorets that might be a normal behavior at the moment, when it goes "crazy" it's because it shows new outputs that have been detected, each tick is an output event.

Using `o/p` allows to navigate blocks (to the next output)

**Comment by YaroShkvorets** [comment]
Ah "thick" block character means many events, empty block means no events in that segment, I see.
Would be nice to show some kind of legend down below.

**Comment by abourget** [comment]
If you find anything, don't hesitate to open a issue! Thanks @YaroShkvorets and @DenisCarriere !

**Pull request merged**
