### PR TITLE
Add Map Vs Stores section and populate with first draft content

### PR DESCRIPTION
**Pull request by seanmooretechwriter**
Add Map Vs Stores section and populate with first draft content.

Please review this initial draft content and let me know if you see any issues, what changes need to be made, and what needs to be added, andprovide a few bullet points for the map area; look for Need Input 01, etc.

### CODE REVIEW

**Comment by Eduard-Voiculescu** [comment]
Hey @seanmooretechwriter, I updated the file with a couple of examples for `map` substreams usage.

**Comment by seanmooretechwriter** [comment]
@Eduard-Voiculescu Thank you for the input and assistance! 

I've made some updates and added a bit more to the document. Would you mind taking another look and letting me know if anything comes to mind that we might be able to add to build it out more? Or do you think we're getting close to providing enough information on maps vs stores?

Thanks again!

**Review by Eduard-Voiculescu — APPROVED** [review]

**Comment by Eduard-Voiculescu** [comment]
LGTM

**Comment by seanmooretechwriter** [comment]
@Eduard-Voiculescu Thanks again for the review and input. I'll get this merged and integrated into the live documentation next.

@maoueh Please let us know if you would like to add, remove or modify any of this content prior to the merge. Thank you.

**Pull request merged**
